services:

  db:
    image: postgres:17
    container_name: postgres-db
    extra_hosts:
      - "localhost:127.0.0.1"
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:

    image: app:1.0.0

    build:
      context: .
      dockerfile: Dockerfile

    container_name: tomee-app
    depends_on:
      - db
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5431/postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=admin
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
